//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaptchaIon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaptchaIon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $(function() {
        ///    $(form).submit(function () {
        ///        alert(&apos;Handler for .submit() called.&apos;);
        ///        return false;
        ///    });
        ///}).
        /// </summary>
        internal static string Captchaion {
            get {
                return ResourceManager.GetString("Captchaion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;
        ///    $(function () {
        ///        $(&quot;form&quot;).submit(function () {
        ///            if ($(&apos;#textcaptcha&apos;).val().length != $(&apos;#textlength&apos;).val()) {
        ///                $(&apos;.error&apos;).html(&apos;#errortext#&apos;);
        ///                return false;
        ///            }
        ///            return true;
        ///        });
        ///    });
        ///    function doAJAX() {
        ///        $.ajax({
        ///            type: &quot;POST&quot;,
        ///            url: &quot;cp/captcha/rfimage/#ass#&quot;,
        ///            data: JSON.stringify({ &apos;image&apos;: $(&apos;#head-img&apos;).attr(&apos;src&apos;) }),
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CaptchaionHtml {
            get {
                return ResourceManager.GetString("CaptchaionHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rf {
            get {
                object obj = ResourceManager.GetObject("rf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
